### ISSUE TITLE
Not able to find slab/init.scss and slab/init.yuck in eww.

### ISSUE THREAD

**Issue by shauryagoel** [beyond9thousand/dotfiles#3]
Hi @beyond9thousand, thanks for the wonderful dotfiles. I was trying to use your eww configuration in my setup, but, can't find the slab directory, which is imported inside eww.yuck. Do we need to get this directory from somewhere else?

**Comment by beyond9thousand** [comment]
That is not very descriptive, you will need to share a screenshot to show what you mean by bad looking

**Comment by beyond9thousand** [comment]
That's not very descriptive, can you show me a screenshot of what you mean by bad looking?

**Comment by shauryagoel** [comment]
![image](https://user-images.githubusercontent.com/6321314/200163338-0a76f335-0f22-404a-8b1e-3fb5910a3d6c.png)

This is after removing the (include "./yuck/slab/init.yuck") line in eww.yuck.

**Comment by beyond9thousand** [comment]
My best guess is that you might be missing the necessary fonts

**Comment by beyond9thousand** [comment]
Thanks for bringing this to my notice, it is a widget that I have not yet finished writing (barely begun), and therefore did not back it up to my repo. I'm assuming it causes eww to not be able to launch?

**Comment by shauryagoel** [comment]
Yeah, it doesn't launch. However, after commenting the line in eww.yuck, I get a very bad looking bar.

**Comment by shauryagoel** [comment]
I am sure I have installed all of the desired fonts. Moreover, is it a font issue?

**Comment by beyond9thousand** [comment]
Looks to me like a font issue
![image](https://user-images.githubusercontent.com/77363063/200164783-062e8a0b-4686-4d23-947e-624cfc8b931f.png)

**Comment by shauryagoel** [comment]
I have all the fonts installed which are mentioned in the README and also in eww directory. Still I am facing the same issue. I start eww daemon using `eww daemon` and start the taskbar using  `eww open taskbar` as mentioned in the file .bin/control_box in -ewwopen case.

**Comment by beyond9thousand** [comment]
I am using an outdated version of JetBrains nerd font (deliberately), can you check if using that resolves the issue? The reason for doing this is super specific, you can refer [this](https://github.com/ryanoasis/nerd-fonts/issues/896#issuecomment-1272407990) issue to see why. These are the two packages on my system.

```
local/nerd-fonts-jetbrains-mono-160 2.1.0-1
    A Nerd Font patched version of JetBrains Mono, version with patched nbsp
local/ttf-jetbrains-mono 2.242-2
    Typeface for developers, by JetBrains
```

**Comment by shauryagoel** [comment]
So I installed both the fonts which you mentioned, but, it was still showing the same bar. However, after noticing that in eww.scss there was a slab import at line 48, I commented that part and now everything is working as expected.

Once again thanks for your configuration. I will be eagerly waiting for your slab modules.

**Comment by beyond9thousand** [comment]
I updated the repo to include the two folders since you first opened this issue, so removing those comments should work just as well. Regardless, glad you were able to solve your problem
