### ISSUE TITLE
tried to replicate your setup, but failed.

### ISSUE THREAD

**Issue by al3rez** [beyond9thousand/dotfiles#5]
you haven an amazing setup, i tried to setup eww and bspwm but i'm having trouble displaying the icons and etc;

i'm using Ubuntu 22.04, could you please send me your fonts? i downloaded the recent Phosphor but it doen't show properly, also the workspaces aren't defined in bspwpm.

**Comment by al3rez** [comment]
![Uploading 2023-12-29-101123_2560x1440_scrot.png…]()

**Comment by al3rez** [comment]
![image](https://github.com/beyond9thousand/dotfiles/assets/15009059/1912357a-bdb2-4a6a-938d-b45d4c1be82b)

**Comment by beyond9thousand** [comment]
you will find the workspaces defined in [bspc-configs.sh](https://github.com/beyond9thousand/dotfiles/blob/master/.config/bspwm/configs/bspc-configs.sh)

fonts have also been linked here [fonts](https://github.com/beyond9thousand/dotfiles/tree/master#ab-fonts)
